### ISSUE TITLE
Could not create the .modio/ directory, retying with alternative path: C:/users/steam/My Documents

### ISSUE THREAD

**Issue by hoangvu12** [M7mdBinGhaith/MordhauWine#1]
Everytime booting up the server, the server have to reinstall the mods again because the server failed to create .modio directory inside `/Mordhau/Content/.`

![image](https://github.com/M7mdBinGhaith/MordhauWine/assets/68330291/72425fb7-61fb-4fad-a316-e4ff4119fcc2)

**Comment by M7mdBinGhaith** [comment]
Well, I have not played Mordhau for more than a year. I was aware of such an issue, but it was only applicable when you delete the container, not when you restart it. When I have time, I'll take a look at it.

**Comment by hoangvu12** [comment]
> Well, I have not played Mordhau for more than a year. I was aware of such an issue, but it was only applicable when you delete the container, not when you restart it. When I have time, I'll take a look at it.

I think that because I was doing `docker compose up` and `docker compose down` instead of `docker compose start` and `docker compose stop`. I realized that when I was trying other mordhau wine image.

**Comment by M7mdBinGhaith** [comment]
Guess that was the issue then. you should just use docker start <container_name>. no need for compose after initial spin up.

**Comment by hoangvu12** [comment]
Yea I think that's the problem.
